---
# main.yml

- name: Install system packages
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_packages }}"

- name: Local nagios plugins path
  file:
    path: "{{ nagios.plugins_path }}"
    recurse: True
    state: directory

- name: Install NRPE plugins
  copy:
    dest: "{{ nagios.plugins_path }}"
    mode: 0755
    src: plugins/

- name: Add NRPE to sudoers
  template:
    dest: /etc/sudoers.d/nrpe
    mode: 0440
    src: nrpe_sudoer.j2
    validate: "/usr/sbin/visudo -cf %s"
  notify: Restart NRPE

- name: Allow from nagios server hosts
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    line: allowed_hosts={{ ','.join(nagios.allowed_hosts) }}
    regexp: "^allowed_hosts=.*"
  notify: Restart NRPE

- name: Add local nrpe definitions
  template:
    dest: "{{ nagios.nrpe_path }}"
    src: nrpe_command.cfg.j2
  notify: Restart NRPE
