---
# packages.yml

- name: Zypper repositories
  command: zypper addrepo {{ item.repo }} {{ item.name }}
  args:
    creates: /etc/zypp/repos.d/{{ item.name}}.repo
  with_items: "{{ opensuse_repos }}"
  when: ansible_os_family == 'Suse'

- name: Install system packages
  apt:
    name: "{{ ubuntu_packages }}"
  when: ansible_os_family == 'Debian'

- name: Install system packages
  zypper:
    name: "{{ opensuse_packages }}"
  when: ansible_os_family == 'Suse'
