---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
    release: "0.1"
  name: $SERVICE_NAME
spec:
  replicas: $K8S_WORKER_COUNT
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
      release: "0.1"
  serviceName: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
        release: "0.1"
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - { name: DHCP_NETBIOS_NAME_SERVERS, value: $DHCP_NETBIOS_NAME_SERVERS }
        - { name: DHCP_SUBNET1, value: $DHCP_SUBNET1 }
        - { name: DOMAIN, value: $DOMAIN }
        - { name: DNS_SERVER, value: $DNS_SERVERS }
        - { name: DNS_UPSTREAM, value: $DNS_UPSTREAM }
        - { name: NTP_SERVER, value: $NTP_SERVERS }
        - { name: PORT_DNSMASQ_DNS, value: "$PORT_DNSMASQ_DNS" }
        - { name: SUBNET1_GATEWAY, value: $SUBNET1_GATEWAY }
        - { name: SUBNET1_INTERFACE, value: $SUBNET1_INTERFACE }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        securityContext:
          capabilities:
            add: [ NET_ADMIN ]
        volumeMounts:
        - mountPath: /tftpboot/pxelinux
          name: share
          readOnly: true
          subPath: $SERVICE_NAME/pxelinux
        - mountPath: /etc/dhcpd.d/ranges
          name: ranges
        - mountPath: /etc/dhcpd.d/local
          name: admin
          readOnly: true
          subPath: services/$SERVICE_NAME/etc/dhcpd.d
        - mountPath: /etc/dnsmasq.d/local
          name: admin
          readOnly: true
          subPath: services/$SERVICE_NAME/etc/dnsmasq.d
        - mountPath: /var/lib/misc
          name: leases
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
      hostNetwork: true
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      serviceAccountName: $K8S_NAMESPACE-privileged
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: ranges
        configMap:
          name: $SERVICE_NAME-ranges
      - name: share
        hostPath: { path: $PATH_SHR }
  volumeClaimTemplates:
  - metadata:
      name: leases
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 500Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: $SERVICE_NAME-ranges
data:
  $SERVICE_NAME-0: ""
  $SERVICE_NAME-1: $DHCP_RANGE_1
  $SERVICE_NAME-2: $DHCP_RANGE_2
  $SERVICE_NAME-3: ""
  $SERVICE_NAME-4: ""
