---
# packages.yml

- name: Zypper repository
  command: >
    zypper addrepo
    {{ '--no-gpgcheck' if 'disable_gpg_check' in item else ''}}
    {{ item.repo }} {{ item.name }}
  args:
    creates: /etc/zypp/repos.d/{{ item.name}}.repo
  with_items: "{{ opensuse_google_auth_repo }}"
  when: ansible_os_family == 'Suse'

- name: Install PAM module for google-authenticator
  package:
    name: pam-google-authenticator
