---
journald_conf_defaults:
  SystemMaxFiles: 10
  SystemMaxFileSize: 20M

journald_conf_override: {}
journald_conf: "{{ journald_conf_defaults | combine(journald_conf_override) }}"

nagios_defaults:
  allowed_hosts:
  - localhost
  nrpe_cfg: "{{ '/etc/nagios' if ansible_os_family == 'Debian' else '/etc'
    }}/nrpe.cfg"
  nrpe_path: /etc/{{ 'nagios' if ansible_os_family == 'Debian'
    else 'nrpe.d' }}/nrpe_local.cfg
  nrpe_service: "{{ 'nagios-nrpe-server' if ansible_os_family == 'Debian'
    else 'nrpe' }}"
  nrpe_user: nagios
  local_plugins_path: /usr/local/lib/nagios
  plugins_sudo:
  - check_smartmon.py
  - check_splunk_license.sh
  system_plugins_path: /usr/lib/nagios/plugins

nagios_override: {}
nagios: "{{ nagios_defaults | combine(nagios_override) }}"

nrpe_command_defaults:
  data_sync:
    plugin: check_file_age
    options: -w 1800 -c 7200 -f /var/lib/docker/k8s-volumes/sync-logs/data-sync/unison-status.txt
  disk_status:
    local: True
  etcd_cluster_health:
    local: True
    options: -- --endpoints=http://localhost:2379
  load:
    options: -w 15,10,5 -c 30,25,20
  netint_eth0:
    local: True
    plugin: check_netint.pl
    options: -S 1000Mb -n eth0$ -efq
  ntpd_running:
    local: True
    plugin: check_docker_syscod.sh
    options: -n ntpd_app_1 -c 5,10 -m 5,7 -s

nrpe_command_override: {}
nrpe_commands: "{{ nrpe_command_defaults | combine(nrpe_command_override) }}"

opensuse_packages:
  - monitoring-plugins-load
  - monitoring-plugins-procs
  - nrpe
  - smartmontools

opensuse_repos:
  - name: oss
    repo: http://download.opensuse.org/distribution/leap/42.2/repo/oss/suse

ubuntu_packages:
  - bc
  - nagios-nrpe-server
  - smartmontools
  - snmpd
  - sysstat
  # deprecated
  # - mcelog

ubuntu_packages_extra:
  - etcd-client
