---
local_group_defaults:
  nagcmd: 486
  nrpe: 552
  users: 100

local_group_additions: {}
local_groups: "{{ local_group_defaults | combine(local_group_additions) }}"

myth_user_defaults:
  - name: mythtv
    uid: 1001
    comment: MythTV Frontend
    group: users
    shell: /bin/bash
    groups: video
  - name: nrpe
    uid: 2025
    comment: NRPE monitoring
    createhome: no
    group: nrpe
    groups: nagcmd

myth_user_additions: []
myth_users: "{{ myth_user_defaults + myth_user_additions }}"

opensuse_google_auth_repo:
  - name: oss
    repo: http://download.opensuse.org/distribution/leap/42.2/repo/oss/suse

pam_package: "{{
    'libpam-google-authenticator' if ansible_os_family == 'Debian' 
    else 'pam-google-authenticator' }}"

ubuntu_repo_uri: http://archive.ubuntu.com/ubuntu/

ubuntu_google_auth_repo:
  - deb {{ ubuntu_repo_uri }} xenial main restricted universe multiverse
