variables:
  IMAGE: git-pull

stages:
  - Static Code Analysis
  - Create Image
  - Push Image
  - Functional Tests
  - Promote Image
  - Clean

before_script:
  - export TAG=bld_$CI_PIPELINE_IID_${CI_COMMIT_SHA:0:7}

.registry_template: &registry_login
  before_script:
  - export TAG=bld_$CI_PIPELINE_IID_${CI_COMMIT_SHA:0:7}
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $REGISTRY
  image: docker:19.03.8
  services: [ "docker:dind" ]

analysis:
  stage: Static Code Analysis
  image: instantlinux/python-builder:latest
  script: cd images/$IMAGE && make analysis

create_image:
  stage: Create Image
  script:
  - docker build -t $IMAGE:$TAG -f images/$IMAGE/Dockerfile images/$IMAGE
      --build-arg=VCS_REF=$CI_COMMIT_SHA
      --build-arg=BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%SZ)

push_image:
  stage: Push Image
  <<: *registry_login
  script:
  - docker tag $IMAGE:$TAG $REGISTRY/$IMAGE:$TAG
  - docker push $REGISTRY/$IMAGE:$TAG

test:
  stage: Functional Tests
  image: instantlinux/python-builder:latest
  script: cd images/$IMAGE && make test_functional

promote_image:
  only: {refs: [master]}
  stage: Promote Image
  <<: *registry_login
  script:
  - docker tag $IMAGE:$TAG $REGISTRY/$IMAGE:latest
  - docker push $REGISTRY/$IMAGE:latest

clean:
  stage: Clean
  script: docker rmi $REGISTRY/$IMAGE:$TAG
  when: always
