# created 30-may-20 by richb@instantlinux.net

stages:
  - prepare
  - images

image: docker:19.03.8

prepare:
  stage: prepare
  script:
  - IMAGES=$(find images -maxdepth 1 -exec basename {} \;)
  - for IMG in $IMAGES; do
      sed -e "s/{{ IMAGE }}/$IMG/" .image-gitlab-ci.yml  > .child-$IMG.yml;
    done
  artifacts:
    paths: [ .child-*.yml ]

git-dump:
  stage: images
  trigger:
    include:
    - artifact: .child-$CI_JOB_NAME.yml
      job: prepare

git-pull:
  stage: images
  trigger:
    include:
    - artifact: .child-$CI_JOB_NAME.yml
      job: prepare
