# created 30-may-20 by richb@instantlinux.net

stages:
  - prepare
  - image1
  - images

image: docker:19.03.8

prepare:
  stage: prepare
  script:
  - IMAGES=$(find images -maxdepth 1 -exec basename {} \;)
  - for IMG in $IMAGES; do
      sed -e "s/{{ IMAGE }}/$IMG/" .image-gitlab-ci.yml  > .child-$IMG.yml;
    done
  artifacts:
    paths: [ .child-*.yml ]

# TODO: this is an egregious case of non-DRY code. Each could be
# reduced from 6 lines to 2 if the artifact could be specified as
# .child-$CI_JOB_NAME.yml. But that is not possible until a 2017
# feature request is eventually implemented:
# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1809

git-dump:
  stage: image1
  trigger:
    include:
    - artifact: .child-git-dump.yml
      job: prepare

git-pull:
  stage: images
  trigger:
    include:
    - artifact: .child-git-pull.yml
      job: prepare
    strategy: depend
