# created 30-may-20 by richb@instantlinux.net

stages:
  - prepare
  # - git-dump
  # - git-pull
  # - python-builder
  - python-wsgi

image: docker:19.03.8

prepare:
  stage: prepare
  script:
  - IMAGES=$(find images -maxdepth 1 -exec basename {} \;)
  - for IMG in $IMAGES; do
      sed -e "s/{{ IMAGE }}/$IMG/" .image-gitlab-ci.yml  > .child-$IMG.yml;
    done
  artifacts:
    paths: [ .child-*.yml ]

# TODO: this is an egregious case of non-DRY code. Each could be
# reduced to 2 lines by variable interpolation -- for example, the
# artifact could be specified as .child-$CI_JOB_NAME.yml. But that is
# not possible until a 2017 feature request is eventually implemented:
# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1809

# TODO: figure out why these have to be assigned to separate stages,
# without waiting for completion (strategy: depend); putting more than
# one in a stage gives "unknown failure"

git-dump:
  stage: git-dump
  trigger:
    include:
    - artifact: .child-git-dump.yml
      job: prepare
  only:
    changes: [ images/git-dump/**, lib/**, .image-gitlab-ci.yml ]

git-pull:
  stage: git-pull
  trigger:
    include:
    - artifact: .child-git-pull.yml
      job: prepare
    # strategy: depend
  only:
    changes: [ images/git-pull/**, lib/**, .image-gitlab-ci.yml ]

python-builder:
  stage: python-builder
  trigger:
    include:
    - artifact: .child-python-builder.yml
      job: prepare
    # strategy: depend
  only:
    changes: [ images/python-builder/**, lib/**, .image-gitlab-ci.yml ]

python-wsgi:
  stage: python-wsgi
  trigger:
    include:
    - artifact: .child-python-wsgi.yml
      job: prepare
    # strategy: depend
  only:
    changes: [ images/python-wsgi/**, lib/**, .image-gitlab-ci.yml ]
