version: "3"
services:

  app:
    image: ${REGISTRY_URI:-instantlinux}/garbd2:latest
    ports:
    - 3306:3306
    - 4444:4444
    - 4567:4567
    - 4568:4568
    command: >
      /usr/bin/garbd -a gcomm://mdb01.ci.net:4567
      -g cluster01 -o pc.wait_prim=no

networks:
  default:
    external:
      name: app_net
