---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: $RSYSLOGD_IP
  ports:
  - name: $SERVICE_NAME
    port: 514
    targetPort: 514
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        volumeMounts:
        - mountPath: /etc/logrotate.d
          name: admin
          readOnly: true
          subPath: services/$SERVICE_NAME/etc/logrotate.d
        - mountPath: /etc/rsyslog.d
          name: admin
          readOnly: true
          subPath: services/$SERVICE_NAME/etc/rsyslog.2
      dnsConfig:
        options:
        - { name: ndots }
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: logs
        emptyDir: {}

