---
# These are only examples: in a group_vars file, override these with
#  your own volumes and network mounts

fs_type: ext4

# LUKS-encrypted volumes
luks_volumes: {}
# backup:
#   inodes: 100
#   path: /var/lib/docker/volumes/backup/_data
#   size: 100
#   vg: data01

# Unencrypted local volumes
local_volumes:
  tmpfs:
    path: /tmp
    options: nodev,nosuid,nodiratime,size=1000M
    type: tmpfs

# Network volumes
network_mounts:
  nfs:/service:
    path: /var/mounted
    options: _netdev,ro,soft
    type: nfs

cifs_credentials:
  file: /etc/security/cifs-credentials.txt
  local_user: www-data
  remote_user: nobody

masterkey:
  path: /master
  host: 10.10.0.2
  sshkey_private: /root/.ssh/master.pem
  user: master

ubuntu_packages:
  - cifs-utils
  - cryptsetup
  - nfs-client
  - sshfs
