---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: HOST, value: $DYNAMIC_HOSTNAME }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        volumeMounts:
        - name: secret
          mountPath: /run/secrets/ez-ipupdate-user
          readOnly: true
          subPath: ez-ipupdate-user
      dnsConfig:
        options:
        - { name: ndots }
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: secret
        secret:
          secretName: ez-ipupdate-user
