version: "3.1"

services:

  app:
    image: dockerhub.instantlinux.net:5000/ez-ipupdate:latest
    environment:
      HOST: dolores.ci.net
    secrets:
    - ez-ipupdate-user

networks:
  default:
    external:
      name: app_net
secrets:
  ez-ipupdate-user:
    external: true
