---
- name: Cryptsetup resize
  command: cryptsetup resize luks-{{ item.key }}
  with_dict: "{{ luks_volumes }}"

- name: Filesystem resize
  command: resize2fs /dev/mapper/luks-{{ item.key }}
  with_dict: "{{ luks_volumes }}"
