---
- name: Cryptsetup resize
  command: cryptsetup resize luks-{{ item.key }}
  with_dict: "{{ volumes[vg] }}"

- name: Filesystem resize
  command: resize2fs /dev/mapper/luks-{{ item.key }}
  with_dict: "{{ volumes[vg] }}"
