---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  ports:
  - { port: $PORT_UPSD_1, nodePort: 30493, targetPort: 3493 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: SERIAL, value: $UPS_1_SERIAL }
        image: $REGISTRY_URI/nut-upsd:latest
        # TODO this does not work with pod security policies yet
        securityContext:
          privileged: true
        volumeMounts:
#        - name: usb
#          mountPath: /dev/ttyUSB0
        - name: secret
          mountPath: /run/secrets/nut-upsd-password
          readOnly: true
          subPath: nut-upsd-password
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        service.$SERVICE_NAME: allow
      serviceAccountName: $K8S_NAMESPACE-privileged
      volumes:
#      - name: usb
#        hostPath: { path: /dev/ttyUSB0 }
      - name: secret
        secret:
          secretName: nut-upsd-password
