---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: OX_CONFIG_DB_HOST, value: $DB_HOST }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/open-xchange-appsuite:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /ox/etc
          name: admin
          readOnly: true
          subPath: services/ox-appsuite/etc
        - mountPath: /ox/store
          name: share
          subPath: ox-appsuite/data
        - mountPath: /var/log/open-xchange
          name: logs
        - mountPath: /var/log/apache2
          name: apache2
        - name: ox-db-password
          mountPath: /run/secrets/ox-db-password
          readOnly: true
          subPath: ox-db-password
        - name: ox-admin-password
          mountPath: /run/secrets/ox-admin-password
          readOnly: true
          subPath: ox-admin-password
        - name: ox-master-password
          mountPath: /run/secrets/ox-master-password
          readOnly: true
          subPath: ox-master-password
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: logs
        emptyDir: {}
      - name: apache2
        emptyDir: {}
      - name: ox-db-password
        secret:
          secretName: ox-db-password
      - name: ox-admin-password
        secret:
          secretName: ox-admin-password
      - name: ox-master-password
        secret:
          secretName: ox-master-password
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: $SERVICE_NAME.$DOMAIN
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
