---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  ports:
  - { port: 80, targetPort: 80 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/open-xchange-appsuite:latest
        volumeMounts:
        - mountPath: /ox/etc
          name: admin
          readOnly: true
          subPath: ox-appsuite/etc
        - mountPath: /ox/store
          name: share
          subPath: ox-appsuite/data
        - mountPath: /var/log/open-xchange
          name: logs
        - mountPath: /var/log/apache2
          name: apache2
        - name: ox-db-password
          mountPath: /run/secrets/ox-db-password
          readOnly: true
          subPath: ox-db-password
        - name: ox-admin-password
          mountPath: /run/secrets/ox-admin-password
          readOnly: true
          subPath: ox-admin-password
        - name: ox-master-password
          mountPath: /run/secrets/ox-master-password
          readOnly: true
          subPath: ox-master-password
      imagePullSecrets:
      - name: regcred
      ports:
      - containerPort: 80
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: logs
        emptyDir: {}
      - name: apache2
        emptyDir: {}
      - name: ox-db-password
        secret:
          secretName: ox-db-password
      - name: ox-admin-password
        secret:
          secretName: ox-admin-password
      - name: ox-master-password
        secret:
          secretName: ox-master-password
