---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: API_TOKEN_SECRET, value: git.$MYDOMAIN-api-token }
        - { name: REPO_PREFIX, value: "git@git.$MYDOMAIN:richb/" }
        - { name: SSH_PORT, value: "$PORT_GITLAB_SSH" }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/git-dump:latest
        volumeMounts:
        - mountPath: /var/backup
          name: backup
          subPath: $SERVICE_NAME
        - mountPath: /var/log
          name: logs
        - name: secret-sshkey
          mountPath: /run/secrets/git-dump_sshkey
          readOnly: true
          subPath: git-dump-sshkey
        - name: secret-token
          mountPath: /run/secrets/git.$MYDOMAIN-api-token
          readOnly: true
          subPath: git.$MYDOMAIN-api-token
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        service.$SERVICE_NAME: allow
      volumes:
      - name: backup
        hostPath: { path: $PATH_BKP }
      - name: logs
        hostPath: { path: $K8S_VOLUMES_PATH/sync-logs/$SERVICE_NAME }
      - name: secret-sshkey
        secret:
          secretName: git-dump-sshkey
      - name: secret-token
        secret:
          secretName: git.$MYDOMAIN-api-token
