---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  ports:
  - name: $SERVICE_NAME
    port: 80
    targetPort: 8081
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: DB_HOST, value: $DB_HOST }
        - { name: DB_PASSWORD, value: $DB_PASSWORD }
        - { name: DB_TYPE, value: $DB_TYPE }
        - { name: TZ, value: $TZ }
        image: docker.bintray.io/jfrog/artifactory-oss:$VERSION_ARTIFACTORY
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: data
          mountPath: /var/opt/jfrog/artifactory
          subPath: $SERVICE_NAME/data
        - name: data
          mountPath: /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.40-bin.jar
          readOnly: true
          subPath: $SERVICE_NAME/mysql-connector-java-5.1.40.jar
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: data
        hostPath: { path: $PATH_SHR }
