---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  ports:
  - { port: 80, targetPort: 8081, name: $SERVICE_NAME }
  - { port: $PORT_NEXUS_REGISTRY, targetPort: 5000, name: registry }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: -Xms1536m -Xmx2048m -XX:MaxDirectMemorySize=3g
        - { name: TZ, value: $TZ }
        image: sonatype/nexus3:$VERSION_NEXUS
        ports:
        - containerPort: 5000
        - containerPort: 8081
        volumeMounts:
        - mountPath: /nexus-data
          name: $SERVICE_NAME
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: $SERVICE_NAME
        hostPath: { path: $K8S_VOLUMES_PATH/$SERVICE_NAME }
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: $SERVICE_NAME.$MYDOMAIN
    hosts:
    - $SERVICE_NAME.$MYDOMAIN
  rules:
  - host: $SERVICE_NAME.$MYDOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
