---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $VOLUME_NAME
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: $K8S_VOLUMES_PATH/$VOLUME_NAME
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - $NODENAME
