---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  ports:
  - { port: 80, targetPort: 80 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: WORDPRESS_DB_HOST, value: $DB_HOST }
        - { name: WORDPRESS_DB_NAME, value: $SERVICE_NAME }
        - { name: WORDPRESS_DB_USER, value: wordpress }
        - { name: TZ, value: $TZ }
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME
              key: WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME
              key: WORDPRESS_AUTH_KEY
        - name: WORDPRESS_SECURE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME
              key: WORDPRESS_SECURE_AUTH_KEY
        - name: WORDPRESS_LOGGED_IN_KEY
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME
              key: WORDPRESS_LOGGED_IN_KEY
        - name: WORDPRESS_NONCE_KEY
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME
              key: WORDPRESS_NONCE_KEY
        - name: WORDPRESS_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME
              key: WORDPRESS_AUTH_SALT
        - name: WORDPRESS_SECURE_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME
              key: WORDPRESS_SECURE_AUTH_SALT
        - name: WORDPRESS_NONCE_SALT
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME
              key: WORDPRESS_NONCE_SALT
        image: wordpress:$VERSION_WORDPRESS
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/etc/php/conf.d/ci-php.ini
          name: admin
          readOnly: true
          subPath: services/wordpress/ci-php.ini
        - mountPath: /var/www/html
          name: share
          subPath: $SERVICE_NAME/html
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: share
        hostPath: { path: $PATH_SHR }
