version: "3"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/duplicati:latest
    environment:
      PUID: 0
      TZ: ${TZ:-UTC}
    ports:
    - ${PORT_DUPLICATI:-8200}:8200
    volumes:
    - config:/config
    - backups:/backups
    - restore:/restore
    # list of volumes to back up, customize as needed
    - /home:/backup/home:ro

volumes:
  backups:
  config:
  restore:
