---
# defaults

vg: data01

docker_defaults:
  apt_repo:
    key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    package_name: docker-ce
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial edge
    url: https://download.docker.com/linux/ubuntu/gpg
  certs:
    ca_root: ca-root.pem
    path: /root/certs
  compose:
    sha256: acfa66dba77dac9635ff9b195ccea81768eb009ce9c9f1181c000eb95effb963
    version: 1.15.0
  local_volumes: /var/lib/docker/volumes
  share_path: /var/lib/docker/share
  thinpool:
    autoextend_percent: 20
    autoextend_threshold: 80
    meta_size: 100
    size: 2000
  options:
    hosts:
    - tcp://0.0.0.0:2376
    - unix:///var/run/docker.sock
    storage-driver: devicemapper
    storage-opts:
    - dm.thinpooldev=/dev/mapper/{{ vg }}-thinpool
    - dm.use_deferred_removal=false
    - dm.use_deferred_deletion=false
    tls: True
    tlscacert: /root/certs/ca-root.pem
    tlscert: /root/certs/docker-tls-cert.pem
    tlskey: /root/certs/docker-tls-key.pem
    tlsverify: True

docker_override: {}
docker: "{{ docker_defaults | combine(docker_override) }}"

kernel:
  long_ver: 4.4.79-040479.201707271932
  origin: http://kernel.ubuntu.com/~kernel-ppa/mainline
  short_ver: "040479"
  version: 4.4.79

sysctl:
  fs.inotify.max_user_watches: 65536

syslog:
  host: syslog
  port: 514

system_paths:
  ca_certs: /usr/local/share/ca-certificates

ubuntu_packages:
  - libpam-google-authenticator
  - python
  - python-pip
  - thin-provisioning-tools

ubuntu_repo_uri: http://archive.ubuntu.com/ubuntu/

ubuntu_repos:
  - deb {{ ubuntu_repo_uri }} xenial main restricted universe multiverse
  - deb {{ ubuntu_repo_uri }} xenial-updates main restricted universe multiverse
  - deb {{ ubuntu_repo_uri }} xenial-backports main restricted universe multiverse
  - deb {{ ubuntu_repo_uri }} xenial-security main restricted universe multiverse

local_group_defaults:
  docker: 485
  nagcmd: 486
  nagios: 499
  nrpe: 552
  repo: 565

local_group_additions: {}
local_groups: "{{ local_group_defaults | combine(local_group_additions) }}"

local_users: {}
