# defaults

docker:
  certs:
    path: /root/certs
    ca_root: ca-root.pem
  thinpool:
    size: 2000
    meta_size: 100
    autoextend_threshold: 80
    autoextend_percent: 20
  options:
    hosts:
    - tcp://0.0.0.0:2376
    - unix:///var/run/docker.sock
    storage-driver: devicemapper
    storage-opts:
    - dm.thinpooldev=/dev/mapper/data01-thinpool
    - dm.use_deferred_removal=false
    - dm.use_deferred_deletion=false
    tls: true
    tlscacert: /root/certs/ca-root.pem
    tlscert: /root/certs/docker-tls-cert.pem
    tlskey: /root/certs/docker-tls-key.pem
    tlsverify: true

kernel:
  version: 4.11.10
  short_ver: "041110"
  long_ver: 4.11.10-041110.201707121132
  origin: http://kernel.ubuntu.com/~kernel-ppa/mainline

ubuntu_packages:
  - bridge-utils
  - libpam-google-authenticator
  - nagios-nrpe-server
  - python
  - python-pip
  - thin-provisioning-tools

network_mode: dhcp
network:
  bridge: br0
  interface: enp0s3
  address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  netmask: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['netmask'] }}"
  gateway: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['gateway'] }}"
  nameservers: "{{ hostvars[inventory_hostname]['ansible_dns']['nameservers'] }}"
  search: "{{ hostvars[inventory_hostname]['ansible_dns']['search'] }}"
  
ntp:
  servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org

syslog:
  host: syslog
  port: 514

local_groups:
  docker: 485
  nagcmd: 486
  nagios: 499
  nrpe: 552
  repo: 565

local_users:
  repo:
    uid: 2012
    comment: Repository manager
    createhome: no
    group: repo
