---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - { port: 80, targetPort: 8080 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: ARTIFACTORY_URI, value: "https://repo.$DOMAIN/artifactory" }
        - { name: ARTIFACTORY_USER, value: jenkins }
        - { name: JAVA_OPTS, value: -Xmx2048m -Djenkins.install.runSetupWizard=false }
        - { name: JENKINS_URL, value: "https://jenkins.$DOMAIN" }
        - { name: SMTP_ADMIN_ADDRESS, value: "Jenkins <jenkins@$DOMAIN>" }
        - { name: SMTP_SMARTHOST, value: smtp.$DOMAIN }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/jenkins-master:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 6144Mi
          requests:
            cpu: 100m
            memory: 3072Mi
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: share
          subPath: jenkins_home
        - mountPath: /var/jenkins_backup
          name: backup
          subPath: $SERVICE_NAME
        - mountPath: /run/secrets/artifactory-user-password
          name: artifactory-user-password
          readOnly: true
          subPath: artifactory-user-password
        - mountPath: /run/secrets/jenkins-admin-password
          name: jenkins-admin-password
          readOnly: true
          subPath: jenkins-admin-password
      dnsConfig:
        options: [ name: ndots ]
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      volumes:
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: backup
        hostPath: { path: $PATH_BKP }
      - name: artifactory-user-password
        secret:
          secretName: artifactory-user-password
      - name: jenkins-admin-password
        secret:
          secretName: jenkins-admin-password
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME-slave
  name: $SERVICE_NAME-slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME-slave
    spec:
      containers:
      - name: $SERVICE_NAME-slave
        env:
        - { name: SWARM_JENKINS_SECRET, value: jenkins-agent-password }
        - { name: SWARM_JENKINS_USER, value: svc_jenkins }
        - { name: SWARM_MASTER_URL, value: "http://$(JENKINS_SERVICE_HOST)" }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/jenkins-slave:latest
        volumeMounts:
#        - mountPath: /var/run/docker.sock
#          name: docker-socket
        - mountPath: /run/secrets/jenkins-agent-password
          name: jenkins-agent-password
          readOnly: true
          subPath: jenkins-agent-password
      dnsConfig:
        nameservers: [ $DNS_SERVERS ]
        options:
        - name: use-vc
        - name: ndots
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        service.jenkins-slave: allow
#      serviceAccountName: $K8S_NAMESPACE-privileged
      volumes:
#      - name: docker-socket
#        hostPath: { path: /var/run/docker.sock }
      - name: jenkins-agent-password
        secret:
          secretName: jenkins-agent-password
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-totp
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$AUTHELIA_IP/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://authtotp.$DOMAIN
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /login
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
