---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pictures
  labels:
    volume.group: pictures
spec:
  capacity:
    storage: 1Mi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /pc/Pictures
    server: $NFS_HOST
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pictures
  namespace: $K8S_NAMESPACE
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Mi
  selector:
    matchLabels:
      volume.group: pictures
  storageClassName: nfs-client
