---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: user
  labels:
    volume.group: user
spec:
  capacity:
    storage: 1Mi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /u
    server: $NFS_HOST
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user
  namespace: $K8S_NAMESPACE
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Mi
  selector:
    matchLabels:
      volume.group: user
  storageClassName: nfs-client
