---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io.service: $SERVICE_NAME
    release: "0.1"
  name: $SERVICE_NAME
  namespace: $K8S_NAMESPACE
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io.service: $SERVICE_NAME
      release: "0.1"
  serviceName: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io.service: $SERVICE_NAME
        release: "0.1"
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: SYNC_INTERVAL, value: "2" }
        - { name: TZ, value: $TZ }
        - name: SYNC_SSHKEY
          valueFrom:
            configMapKeyRef:
              name: $SERVICE_NAME
              key: sync-sshkey
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        ports:
        - containerPort: 22
        volumeMounts:
        - name: archive
          mountPath: /root/.unison
        - name: admin
          mountPath: /etc/unison.d
          readOnly: true
          subPath: services/$SERVICE_NAME
        - name: etc
          mountPath: /etc/ssh
        - name: logs
          mountPath: /var/log/unison
        - name: share
          mountPath: /var/data-sync
        - name: data-sync-sshkey
          mountPath: /run/secrets/data-sync-sshkey
          readOnly: true
          subPath: data-sync
      dnsConfig:
        options:
        - { name: ndots }
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        service.$SERVICE_NAME: allow
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: data-sync-sshkey
        secret:
          secretName: data-sync-sshkey
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: archive
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 500Mi
  - metadata:
      name: etc
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 500Mi
  - metadata:
      name: share
    spec:
      accessModes: [ ReadWriteMany ]
      resources:
        requests:
          storage: 8Gi
      selector:
        matchLabels:
          volume.group: share
---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  labels:
    app.kubernetes.io.service: $SERVICE_NAME
  namespace: $K8S_NAMESPACE
spec:
  clusterIP: None
  ports:
  - { port: 22, targetPort: 22 }
  selector:
    app.kubernetes.io.service: $SERVICE_NAME
    release: "0.1"
