---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  ports:
  - name: $SERVICE_NAME
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: HOSTNAME, value: davite.$DOMAIN }
        - { name: SMTP_PORT, value: "25" }
        - { name: SMTP_SMARTHOST, value: smtp.$DOMAIN }
        - { name: TCP_PORT, value: "" }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/adm/DaVite_Data
          subPath: $SERVICE_NAME
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: data
        hostPath: { path: $PATH_SHR }
