---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - { port: 80, targetPort: 80 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: HOSTNAME, value: davite.$DOMAIN }
        - { name: SCHEME, value: https }
        - { name: SMTP_PORT, value: "25" }
        - { name: SMTP_SMARTHOST, value: smtp.$DOMAIN }
        - { name: TCP_PORT, value: "" }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$SERVICE_NAME:$VERSION_DAVITE
        ports:
        - containerPort: 80
        volumeMounts:
        - name: share
          mountPath: /var/adm/DaVite_Data
          subPath: $SERVICE_NAME
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      volumes:
      - name: share
        hostPath: { path: $PATH_SHR }
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE_NAME
          servicePort: 80
