---
- name: k8s repo key
  apt_key:
    url: "{{ k8s.apt_repo.url }}"

- name: k8s repo
  apt_repository:
    filename: k8s
    repo: "{{ k8s.apt_repo.repo }}"

- name: Install system packages
  apt:
    name: "{{ ubuntu_packages }}"
  when: ansible_os_family == 'Debian'

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
  with_items: "{{ k8s_kernel_modules }}"

- name: Add kernel modules to /etc/modules-load.d
  copy:
    content: "{{ k8s_kernel_modules | join('\n') | string }}"
    dest: /etc/modules-load.d/network.conf

- name: Look for swap entries
  shell: grep swap /etc/fstab | awk '{ print $1; }'
  register: swapdevs

- name: Disable swap
  mount:
    fstype: swap
    path: none
    src: "{{ item }}"
    state: absent
  with_items: "{{ swapdevs.stdout_lines }}"

- name: Turn swap off
  command: swapoff --all
  changed_when: false

- name: Sysctl tuning parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  with_dict: "{{ sysctl }}"

- name: Set up master
  include: master.yml
  when: k8s.master

- name: Join cluster
  include: join.yml
  when: not k8s.master

- name: Add RequiresMountsFor to kubelet.service
  replace:
    dest: /lib/systemd/system/kubelet.service
    regexp: "^\\[Unit\\]$"
    replace: >
      [Unit] 
      \n# Added by Ansible
      \nRequiresMountsFor=/var/lib/kubelet

- name: Add kubelet service
  systemd:
    name: "{{ k8s.service.name }}"
    daemon_reload: yes
    state: "{{ k8s.service.state }}"
    enabled: "{{ k8s.service.enabled }}"
