---
- name: Reset Kubernetes component
  command: kubeadm reset --force
  register: reset_cluster

- name: Set kubeadm configuration
  copy:
    dest: /etc/kubernetes/kubeadm-config.yaml
    content: |
      ---
      apiVersion: kubeadm.k8s.io/v1alpha3
      kind: InitConfiguration
      bootstrapTokens:
      - groups:
        - system:bootstrappers:kubeadm:default-node-token
        token: {{ vault_k8s.join_token }}
        ttl: 1h0m0s
        usages:
        - signing
        - authentication
      localAPIEndpoint:
        advertiseAddress: {{ k8s.master_ip }}
      ---
      apiVersion: kubeadm.k8s.io/v1alpha3
      kind: ClusterConfiguration
      apiServerExtraArgs:
        enable-admission-plugins: PodSecurityPolicy
      controllerManagerExtraArgs:
        address: 0.0.0.0
      kubernetesVersion: {{ k8s.version }}
      networking:
        podSubnet: {{ k8s.pod_network }}
        serviceSubnet: {{ k8s.service_network }}
      schedulerExtraArgs:
        address: 0.0.0.0

- name: Init Kubernetes cluster
  command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  register: init_cluster
  when: reset_cluster is succeeded
