version: "3.1"

services:

  app:
    image: ${REGISTRY_URI:-instantlinux}/postfix:latest
    environment:
      TZ: ${TZ:-UTC}
    volumes:
    - etc:/etc/postfix/postfix.d:ro
    - certs:/etc/ssl/certs:ro
    - spool:/var/spool/postfix
    ports:
    - ${PORT_POSTFIX_EXTERNAL:-25}:25
    secrets:
     - postfix-sasl-passwd
     - webmail.ci.net-server-key.pem 

volumes:
  certs:
  etc:
  spool:
networks:
  default:
    external:
      name: app_net
secrets:
  postfix-sasl-passwd:
    external: true
  webmail.ci.net-server-key.pem:
    external: true
