---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volume.group: $GROUP
  name: $NAME
  namespace: $K8S_NAMESPACE
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  resources:
    requests:
      storage: $VOLUME_SIZE
  storageClassName: local-storage
  selector:
    matchLabels:
      volume.id: "$VOLUME_ID"
