---
# TODO this should be a separate role

- name: bind9 config
  template:
    dest: /etc/bind/named.conf
    src: named.conf.j2
  notify: Restart bind9

- name: Set resolv.conf in place of stub-resolv.conf
  file:
    dest: /etc/resolv.conf
    src: /var/run/systemd/resolve/resolv.conf
    force: True
    state: link

- name: Root hints
  template:
    dest: /etc/bind/root.hint
    src: root.hint.j2

- name: bind9 service
  service:
    name: bind9
    enabled: True
