---
- name: Install system packages
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_packages }}"
  when: ansible_os_family == 'Debian'

- include: bind9.yml
- include: nfs.yml
- include: instantlinux.yml
- include: virtualbox.yml
- include: vsftpd.yml
