---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: SERVER_BANNER, value: '%h Firefly MP3 via Docker' }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        volumeMounts:
        - name: cache
          mountPath: /var/cache/forked-daapd
        - name: music
          mountPath: /srv/music
          readOnly: true
      hostNetwork: true
      imagePullSecrets:
      - name: regcred
      serviceAccountName: $K8S_NAMESPACE-privileged
      volumes:
      - name: cache
        emptyDir: {}
      - name: music
        persistentVolumeClaim:
          claimName: mp3
