---
- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
  with_items: "{{ kernel_modules }}"

- name: Add kernel modules to /etc/modules-load.d
  copy:
    content: "{{ kernel_modules | join('\n') | string }}"
    dest: /etc/modules-load.d/network.conf

- name: Set sysctl tuning parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  with_dict: "{{ network_sysctl }}"
