---
- name: Install system packages
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_packages }}"

- include: network_legacy.yml
  when: ansible_distribution_release != 'bionic'

- include: netplan.yml
  when: ansible_distribution_release == 'bionic'

- name: Set up keepalived (VRRP) for ingress load-balancer
  template:
    dest: /etc/keepalived/keepalived.conf
    mode: 0600
    src: keepalived.conf.j2
  notify: Restart keepalived
  when: network.vrrp_interface
