---
# Tighten security in sshd: lock out brute-force scanners seeking weak ciphers

- name: Set ciphers in sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "(?i)^Ciphers .*"
    line: Ciphers {{ sshd_opts.ciphers|join(',') }}
  notify: Restart sshd

- name: Set macs in sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "(?i)^MACs .*"
    line: MACs {{ sshd_opts.macs|join(',') }}
  notify: Restart sshd

- name: Set kexalgorithms in sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "(?i)^KexAlgorithms .*"
    line: KexAlgorithms {{ sshd_opts.kexalgorithms|join(',') }}
  notify: Restart sshd
