version: "3.1"

services:
  app:
    #image: ${REGISTRY_URI:-instantlinux}/mythtv-backend:latest
    #hostname: ${HOSTNAME_MYTHTV:-mythtv}
    image: mythtv-backend
    hostname: pvr01a
    restart: always
    environment:
      DBNAME: ${DB_MYTHTV:-mythtv}
      DBSERVER: ${DB_HOST:-db00}
      LOCALHOSTNAME: ${HOSTNAME_MYTHTV}
      TZ: US/Pacific
    network_mode: host
    volumes:
    - apache2:/var/log/apache2
    - data:/var/mythdata
    - home:/home/mythtv
    - /var/mythtv:/var/mythtv
    secrets:
    - mythtv-db-password
    - mythtv-user-password

secrets:
  mythtv-db-password:
    file: /var/adm/admin/secrets/mythtv-db-password
  mythtv-user-password:
    file: /var/adm/admin/secrets/mythtv-user-password

volumes:
  apache2:
  data:
  home:
