---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: DBNAME, value: $DB_MYTHTV }
        - { name: DBSERVER, value: $DB_HOST }
        - { name: LOCALHOSTNAME, value: $HOSTNAME_MYTHTV }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        ports:
        - { containerPort: 1900, protocol: UDP }
        - containerPort: 6543
        - containerPort: 6544
        - containerPort: 6545
        - containerPort: 6760
        resources:
          limits:
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: apache-log
          mountPath: /var/log/apache2
        - name: data
          mountPath: /var/mythdata
        - name: share
          mountPath: /home/mythtv
          subPath: $SERVICE_NAME/home
        - name: videos
          mountPath: /var/mythtv/videos
          readOnly: true
        - name: mythposters
          mountPath: /var/mythtv/posters
          readOnly: true
        - name: mytharch1
          mountPath: /var/mythtv/arch1
          readOnly: true
        - name: mytharch2
          mountPath: /var/mythtv/arch2
          readOnly: true
        - name: mytharch3
          mountPath: /var/mythtv/arch3
          readOnly: true
        - name: mytharch4
          mountPath: /var/mythtv/arch4
          readOnly: true
        - name: mytharch5
          mountPath: /var/mythtv/arch5
          readOnly: true
        - name: mytharch0
          mountPath: /var/mythtv/pvr02myth
          readOnly: true
        - name: mythtv-db-password
          mountPath: /run/secrets/mythtv-db-password
          readOnly: true
          subPath: mythtv-db-password
        - name: mythtv-user-password
          mountPath: /run/secrets/mythtv-user-password
          readOnly: true
          subPath: mythtv-user-password
      hostAliases:
      - ip: 127.0.1.1
        hostnames: [ $HOSTNAME_MYTHTV ]
      hostNetwork: true
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        service.$SERVICE_NAME: allow
      serviceAccountName: $K8S_NAMESPACE-privileged
      volumes:
      - name: apache-log
        emptyDir: {}
      - name: data
        hostPath: { path: $K8S_VOLUMES_PATH/mythtv }
      - name: videos
        persistentVolumeClaim:
          claimName: videos
      - name: mythposters
        persistentVolumeClaim:
          claimName: mythposters
      - name: mytharch1
        persistentVolumeClaim:
          claimName: mytharch1
      - name: mytharch2
        persistentVolumeClaim:
          claimName: mytharch2
      - name: mytharch3
        persistentVolumeClaim:
          claimName: mytharch3
      - name: mytharch4
        persistentVolumeClaim:
          claimName: mytharch4
      - name: mytharch5
        persistentVolumeClaim:
          claimName: mytharch5
      - name: mytharch0
        persistentVolumeClaim:
          claimName: mytharch0
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: mythtv-db-password
        secret:
          secretName: mythtv-db-password
      - name: mythtv-user-password
        secret:
          secretName: mythtv-user-password
