version: "3"
services:

  app:
    hostname: artifactory
    ports:
    - 18180:8080
    volumes:
    - /var/dvol/artifactory/data:/artifactory/data
    - /var/dvol/artifactory/logs:/artifactory/logs
    - /var/dvol/artifactory/backup:/artifactory/backup
    image: dockerhub.instantlinux.net:5000/artifactory:5.2.0
    environment:
      TZ: US/Pacific
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.hostname == denali
    networks:
      app_net:

networks:
  app_net:
    external: true
