version: '3'

services:
  authelia:
    image: clems4ever/authelia:v3.2.0
    volumes:
    - ${ADMIN_PATH:-/opt}/authelia/config.yml:/etc/authelia/config.yml:ro
    - ${SHARE_PATH}/authelia/store:/var/lib/authelia/store
    ports:
    - ${PORT_AUTHELIA:-17380}:80
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

  ldap:
    image: dinkel/openldap:latest
    environment:
      SLAPD_ORGANISATION: Community Internet
      SLAPD_DOMAIN: ci.net
      SLAPD_PASSWORD: password
      SLAPD_ADDITIONAL_MODULES: memberof
      SLAPD_ADDITIONAL_SCHEMAS: openldap
      SLAPD_FORCE_RECONFIGURE: 'true'
    volumes:
    - ${ADMIN_PATH:-/opt}/authelia/ldap:/etc/ldap.dist/prepopulate
