version: "3"
services:

  app:
    image: nextcloud:${VERSION_NEXTCLOUD:-latest}
    hostname: cloud.${DOMAIN}
    environment:
      TZ: ${TZ:-UTC}
    ports:
    - ${PORT_CLOUD:-18280}:80
    volumes:
    - ${SHARE_PATH:-/opt}/cloud/html:/var/www/html
    - ${PHOTOS_PATH}/${CLOUD_USER1}:/var/www/html/data/${CLOUD_USER1}/files/Photos
    - ${PHOTOS_PATH}/${CLOUD_USER2}:/var/www/html/data/${CLOUD_USER2}/files/Photos
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

volumes:
  html:
networks:
  default:
    external:
      name: app_net
