version: "3"
services:

  app:
    image: nextcloud:12.0.4
    hostname: cloud.ci.net
    environment:
      TZ: ${TZ:-US/Pacific}
    ports:
    - ${PORT_CLOUD:-18280}:80
    volumes:
    - ${SHARE_PATH:-/opt}/cloud/html:/var/www/html
    - ${PHOTOS_PATH}/richb:/var/www/html/data/richb/files/Photos
    - ${PHOTOS_PATH}/chitof:/var/www/html/data/chitof/files/Photos
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

volumes:
  html:
networks:
  default:
    external:
      name: app_net
