version: "3"
# For VNC console, see URI http://swarm01:4280/vnc.html

services:

  app:
    image: gfjardim/crashplan:latest
    hostname: docker-backup
    environment:
      TZ: ${TZ:-UTC}
      VNC_PASSWD: ${VNC_PASSWD:-crashplan}
    volumes:
    - config:/config
    - backup:/backup
    - /var/lib/docker/swarm:/backup/swarm:ro
    # list of volumes to back up, customize as needed
    - /etc/RCS:/backup/etc/RCS:ro
    - /var/lib/docker/share:/backup/share:ro
    - /home:/backup/home:ro
    - dovecot_inbox:/backup/inbox:ro
    - dovecot_webmail:/backup/webmail:ro
    - sambadc_lib:/backup/sambadc:ro
    ports:
    - ${PORT_CRASHPLAN_VNC:-4280}:4280
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary

volumes:
  config:
  backup:
    external: true
  dovecot_inbox:
    external: true
  dovecot_webmail:
    external: true
  samba_dos:
    external: true
  sambadc_lib:
    external: true
networks:
  default:
    external:
      name: app_net
