version: "3"
services:

  app:
    image: ${REGISTRY_URI:-instantlinux}/duplicati:${VERSION_DUPLICATI:-latest}
    environment:
      PUID: 0
      TZ: ${TZ:-UTC}
    ports:
    - ${PORT_DUPLICATI:-8200}:8200
    volumes:
    - ${SHARE_PATH:-/opt}/duplicati/config:/config
    - backups:/backups
    - restore:/restore
    # list of volumes to back up, customize as needed
    - backup:/backup/services:ro
    - dovecot_inbox:/backup/inbox:ro
    - dovecot_webmail:/backup/webmail:ro
    - /home:/backup/home:ro
    - /pc:/backup/pc:ro
    - proftpd_ftp:/backup/ftp:ro
    - samba_dos:/backup/samba_dos:ro
    - sambadc_lib:/backup/sambadc:ro
    - user_home:/backup/u:ro
    - ${SHARE_PATH}:/backup/share:ro
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == peer

volumes:
  backups:
  restore:
  backup:
    external: true
  dovecot_inbox:
    external: true
  dovecot_webmail:
    external: true
  proftpd_ftp:
    external: true
  samba_dos:
    external: true
  sambadc_lib:
    external: true
  user_home:
    external: true
