version: "3"
services:

  app:
    image: gitlab/gitlab-ce:8.16.4-ce.0
    hostname: git.instantlinux.net
    environment:
      TZ: US/Pacific
    ports:
    - ${PORT_GITLAB_HTTP:-18080}:80
    - ${PORT_GITLAB_SSH:-8999}:22
    # ${PORT_GITLAB_HTTPS:-443}:443
    volumes:
    - ${SHARE_PATH}/gitlab/config:/etc/gitlab
    - ${SHARE_PATH}/gitlab/data:/var/opt/gitlab
    - backup:/var/opt/gitlab/backups
    - logs:/var/log/gitlab
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
    ulimits:
      sigpending: 62793
      nproc: 131072
      nofile: 60000
      core: 0

volumes:
  backup:
    external: true
  logs:
networks:
  default:
    external:
      name: app_net
