version: "3"
services:

  app:
    image: gitlab/gitlab-runner:alpine-v${VERSION_GITLAB_RUNNER}
    volumes:
    - config:/etc/gitlab-runner
    - ${SHARE_PATH:-/opt}/common/pki/ca/instantlinux-ca.crt:/etc/gitlab-runner/certs/ca.crt:ro
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
      replicas: 2

volumes:
  config:
networks:
  default:
    external:
      name: app_net
