version: "3"
services:

  app:
    image: gitlab/gitlab-ce:8.16.4-ce.0
    hostname: git.instantlinux.net
    environment:
      TZ: US/Pacific
    ports:
    - 18080:80
    - 18443:443
    - 8999:22
    volumes:
    - /var/lib/docker/share/gitlab/config:/etc/gitlab
    - /var/lib/docker/share/gitlab/logs:/var/log/gitlab
    - /var/lib/docker/share/gitlab/data:/var/opt/gitlab
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync-member == true
    ulimits:
      sigpending: 62793
      nproc: 131072
      nofile: 60000
      core: 0
    networks:
      app_net:

networks:
  app_net:
    external: true
