version: "3"
services:

  guac:
    hostname: guac
    ports:
    - ${PORT_GUACAMOLE:-16080}:8080
    environment:
      MYSQL_HOSTNAME: ${DB_HOST:-db}
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: ${GUACAMOLE_DBPASS:-guacamole}
      GUACD_HOSTNAME: guacd
    image: glyptodon/guacamole:0.9.11-incubating
  guacd:
    hostname: guacd
    image: glyptodon/guacd:0.9.11-incubating

networks:
  default:
    external:
      name: app_net
