version: "3"
services:

  guac:
    image: guacamole/guacamole:${VERSION_GUACAMOLE:-latest}
    hostname: guac
    ports:
    - ${PORT_GUACAMOLE:-16080}:8080
    environment:
      MYSQL_HOSTNAME: ${DB_HOST:-db}
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: ${GUACAMOLE_DBPASS:-guacamole}
      GUACD_HOSTNAME: guacd
  guacd:
    image: guacamole/guacd:${VERSION_GUACAMOLE:-latest}
    hostname: guacd
