version: "3"
services:
  app:
    hostname: jira
    image: cptactionhank/atlassian-jira:7.3.3
    environment:
      TZ: US/Pacific
    ports:
    - 17080:8080
    volumes:
    - /var/lib/docker/share/jira01/home:/var/atlassian/jira
    - /var/lib/docker/share/jira01/logs:/opt/atlassian/jira/logs
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync-member == true

networks:
  default:
    external:
      name: app_net
