version: "3"
services:
  app:
    hostname: jira
    image: cptactionhank/atlassian-jira:7.7.1
    environment:
      CATALINA_OPTS: -Xms512m -Xmx1280m
      X_PROXY_NAME: jira.${DOMAIN}
      X_PROXY_PORT: 443
      X_PROXY_SCHEME: https
      TZ: ${TZ:-US/Pacific}
    ports:
    - ${PORT_JIRA:-15080}:8080
    volumes:
    - ${SHARE_PATH}/jira01/home:/var/atlassian/jira
    - ${SHARE_PATH}/jira01/logs:/opt/atlassian/jira/logs
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync-member == true

networks:
  default:
    external:
      name: app_net
