version: "3.2"
services:
  app:
    hostname: jira
    image: cptactionhank/atlassian-jira:7.3.3
    environment:
      TZ: US/Pacific
    ports:
    - target: 8080
      published: 15080
      protocol: tcp
      mode: host
    volumes:
    - /var/lib/docker/share/jira01/home:/var/atlassian/jira
    - /var/lib/docker/share/jira01/logs:/opt/atlassian/jira/logs
    deploy:
      placement:
        constraints:
        # node.labels.swarm-sync-member == true
        - node.labels.swarm-sync == peer

networks:
  default:
    external:
      name: app_net
