version: "3"
# image origin cptactionhank/atlassian-jira:7.3.3
services:
  app:
    hostname: jira
    ports:
    - 17080:8080
    volumes:
    - /var/lib/docker/share/jira01/home:/var/atlassian/jira
    - /var/lib/docker/share/jira01/logs:/opt/atlassian/jira/logs
    image: dockerhub.instantlinux.net:5000/atlassian-jira:7.3.3
    environment:
      TZ: US/Pacific
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary
    networks:
      app_net:

networks:
  app_net:
    external: true
