version: "3"
services:

  app:
    image: gliderlabs/logspout:latest
    environment:
      SYSLOG_FORMAT: rfc3164
      TZ: ${TZ:-US/Pacific}
    command: syslog+tcp://${RSYSLOGD_HOST:-syslog}:${PORT_RSYSLOGD:-514}
    volumes:
    - /etc/hostname:/etc/host_hostname:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global

networks:
  default:
    external:
      name: app_net
