version: "3"
services:

  app:
    image: sonatype/nexus3:3.6.2
    hostname: nexus
    environment:
      INSTALL4J_ADD_VM_PARAMS: >
        -Xms1536m -Xmx2048m -XX:MaxDirectMemorySize=3g
      TZ: ${TZ:-US/Pacific}
    ports:
    - ${PORT_NEXUS:-8081}:8081
    - ${PORT_NEXUS_REGISTRY:-5000}:5000
    volumes:
    - /var/lib/docker/share/nexus:/nexus-data
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync-member == true

networks:
  default:
    external:
      name: app_net
