version: "3.2"

services:
  app:
    image: hardware/rainloop:$VERSION_RAINLOOP
    environment:
      GID: ${RAINLOOP_GID:-991}
      UID: ${RAINLOOP_UID:-991}
      LOG_TO_STDOUT: "true"
    ports:
    - ${PORT_RAINLOOP:-8080}:8888
    volumes:
    - ${SHARE_PATH}/rainloop/data:/rainloop/data
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

volumes:
  data:
networks:
  default:
    external:
      name: app_net
