version: "3"
services:

  app:
    hostname: registry
    ports:
    - 5000:5000
    volumes:
    - /var/lib/docker/share/registry:/var/lib/registry
    - /root/certs:/certs
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      TZ: US/Pacific
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync-member == true
    networks:
      app_net:

networks:
  app_net:
    external: true
