version: "3"
services:

  app:
    hostname: registry
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      TZ: US/Pacific
    ports:
    - 5000:5000
    volumes:
    - ${SHARE_PATH}/registry:/var/lib/registry
    - /root/certs:/certs
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync-member == true

networks:
  default:
    external:
      name: app_net
