version: "3"
services:
  app:
    image: wordpress:4.8.0-php7.1-apache
    ports:
    - ${PORT_WORDPRESS_CI:-19380}:80
    environment:
      TZ: ${TZ:-US/Pacific}
      WORDPRESS_DB_HOST: db-wordpress.svc.ci.net
      WORDPRESS_DB_NAME: wordpress_ci
      WORDPRESS_DB_USER: wordpress
    env_file:
    - ${SHARE_PATH}/wordpress-ci/env
    volumes:
    - ${SHARE_PATH}/wordpress-ci/html:/var/www/html
    - ${ADMIN_PATH}/wordpress/ci-php.ini:/usr/local/etc/php/conf.d/ci-php.ini
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 10

networks:
  default:
    external:
      name: app_net
