version: "3"
services:
  app:
    image: wordpress:${VERSION_WORDPRESS:-latest}
    ports:
    - ${PORT_WORDPRESS_IL:-8080}:80
    environment:
      TZ: ${TZ:-UTC}
      WORDPRESS_DB_HOST: ${DB_HOST:-db}
      WORDPRESS_DB_NAME: wordpress_il
      WORDPRESS_DB_USER: wordpress
    env_file:
    - ${SHARE_PATH}/wordpress-il/env
    volumes:
    - ${SHARE_PATH}/wordpress-il/html:/var/www/html
    - ${ADMIN_PATH:-/opt}/wordpress/ci-php.ini:/usr/local/etc/php/conf.d/ci-php.ini:ro
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 10

networks:
  default:
    external:
      name: app_net
