version: "3.2"
services:

  app:
    image: nginx:1.13.0-alpine
    ports:
    - target: 443
      published: 19443
      protocol: tcp
      mode: host
    - target: 80
      published: 19080
      protocol: tcp
      mode: host
    volumes:
    - ${ADMIN_PATH:-/opt}/www00/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    - ${SHARE_PATH}/common/pki/ca:/etc/ssl/ca:ro
    - ${SHARE_PATH}/common/pki/certs:/etc/ssl/certs:ro
    environment:
      TZ: ${TZ:-US/Pacific}
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
      replicas: 3
    secrets:
    - desktop.ci.net-server-key.pem
    - git.instantlinux.net-server-key.pem
    - jenkins.ci.net-server-key.pem
    - jira.ci.net-server-key.pem
    - monitor.ci.net-server-key.pem
    - nexus.instantlinux.net-server-key.pem
    - repo.ci.net-server-key.pem
    - splunk.ci.net-server-key.pem

networks:
  default:
    external:
      name: app_net
secrets:
  desktop.ci.net-server-key.pem:
    external: true
  git.instantlinux.net-server-key.pem:
    external: true
  jenkins.ci.net-server-key.pem:
    external: true
  jira.ci.net-server-key.pem:
    external: true
  monitor.ci.net-server-key.pem:
    external: true
  nexus.instantlinux.net-server-key.pem:
    external: true
  repo.ci.net-server-key.pem:
    external: true
  splunk.ci.net-server-key.pem:
    external: true
