version: "3.2"

services:
  peer:
    image: percona/percona-xtradb-cluster:5.7.17
    environment:
      TZ: US/Pacific
      DISCOVERY_SERVICE: lb01.ci.net:2379
      ETCD_HOST: lb01.ci.net:2379
      CLUSTER_NAME: cluster01
    ports:
    - target: 3306
      published: 13306
      protocol: tcp
      mode: host
    volumes:
    - /var/dvol/xtradb/data:/var/lib/mysql
    - /var/dvol/xtradb/etc:/etc/mysql:ro
    - /var/dvol/xtradb/logs:/var/log/mysql
    deploy:
      mode: global
    networks:
      dbcluster:

networks:
  app_net:
    external: true
  dbcluster:
    external: true
