version: "3"

# Each host's ETCD_NAME should be unique and resolveable in DNS (or use IP addr)
#  Optionally specify $CLUSTER name

# to restart a cluster, generate a new DISCOVERY_TOKEN with desired size
#  DISCOVERY_TOKEN=$(basename `curl -s 'https://discovery.etcd.io/new?size=3'`)
#  export DISCOVERY_TOKEN
# use the same value on each instance
# remove the etcd_data volume, then from services dir invoke:
#  make etcd

services:
  v3:
    image: quay.io/coreos/etcd:v3.2.9
    restart: always
    hostname: ${ETCD_NAME:-v3}
    volumes:
    - data:/var/etcd
    ports:
    - ${PORT_ETCD_CLIENT:-2379}:2379
    - ${PORT_ETCD_PEER:-2380}:2380
    network_mode: host
    command: >
      sh -c "apk add --update ca-certificates &&
      /usr/local/bin/etcd \
        -advertise-client-urls http://${ETCD_NAME:-v3}:2379 \
        -data-dir /var/etcd \
        -discovery https://discovery.etcd.io/${DISCOVERY_TOKEN} \
        -initial-advertise-peer-urls http://${ETCD_NAME:-v3}:2380 \
        -initial-cluster-token ${CLUSTER:-etcd-cluster-1} \
        -listen-client-urls http://0.0.0.0:2379 \
        -listen-peer-urls http://0.0.0.0:2380 \
        -name ${ETCD_NAME:-v3}"

volumes:
  data:
