---
# main.yml
#
# This is heavily customized, replace with your own volume definitions

- name: Install system packages
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_packages }}"

- name: Create mount points
  file:
    dest: "{{ item.value.path }}"
    state: directory
    recurse: true
  with_dict: "{{ volumes[vg] | combine(network_mounts) |
                 combine(local_volumes) }}"

- name: Create volumes
  lvol:
    lv: "{{ item.key }}"
    vg: "{{ vg }}"
    size: "{{ item.value.size }}"
  with_dict: "{{ volumes[vg] }}"

- include: encrypted.yml

- name: Network and local fstab entries
  mount:
    fstype: "{{ item.value.type if 'type' in item.value else fs_type }}"
    path: "{{ item.value.path }}"
    src: "{{ item.key }}"
    opts: "{{ item.value.options if 'options' in item.value else 'default' }}"
    state: mounted
  with_dict: "{{ network_mounts | combine(local_volumes) }}"
