version: "3.1"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/il-v1:latest
    environment:
      DB_HOST: db00.ci.net
      FQDN: homebase.instantlinux.net
      REMOTES: cumbre.ci.net k2.ci.net
      TZ: US/Pacific
    ports:
    - ${PORT_IL_V1:-8080}:80
    volumes:
    - ${SHARE_PATH:-/var}/ilinux/arch:/var/run/ilinux/arch
    - logs:/var/log
    - tmp:/var/www/htdocs/il/app/tmp
    secrets:
    - il_capi_sshkey
    - il_proxy_sshkey
    - il-v1-db-password
    - ilclient-password
    - ilinux-password
    - mysql-backup
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

volumes:
  logs:
  tmp:
networks:
  default:
    external:
      name: app_net
secrets:
  il_capi_sshkey:
    external: true
  il_proxy_sshkey:
    external: true
  il-v1-db-password:
    external: true
  ilclient-password:
    external: true
  ilinux-password:
    external: true
  mysql-backup:
    external: true
