---
# intel.yml

- name: Load intel driver at startup
  template:
    dest: "{{ x11_config_path }}/20-{{ display_driver.type }}.conf"
    src: 20-{{ display_driver.type }}.conf.j2

- name: Limit screen resolution to specified list
  template:
    dest: "{{ x11_config_path }}/20-screen.conf"
    src: 20-screen.conf.j2
