---
# main.yml

- set_fact:
    distro: "{{ 'opensuse' if ansible_os_family == 'Suse' else 'ubuntu' }}"

- include: "{{ distro }}/packages.yml"
- include: "{{ distro }}/lirc.yml"
- include: autosuspend.yml
  when: "suspend"

- include: nvidia.yml
- include: setup.yml
- include: "{{ distro }}/desktop.yml"
