---
# nvidia.yml

- name: Blacklist nouveau driver
  copy:
    content: "blacklist nouveau"
    dest: /etc/modprobe.d/50-nvidia.conf
  notify: Rebuild initrd

- name: NVIDIA driver download
  get_url:
    checksum: sha256:{{ nvidia_driver.checksum }}
    dest: /var/tmp/NVIDIA-Linux.run
    mode: 0755
    url: "{{ nvidia_driver.download_uri }}/{{ nvidia_driver.version
      }}/NVIDIA-Linux-x86_64-{{ nvidia_driver.version }}.run"

# If this fails, most likely there isn't an Nvidia GPU on the
# target system, or the nouveau driver hasn't been deinstalled
# Nouveau driver requires blacklisting, then mkinitrd, then reboot

- name: NVIDIA driver install
  command: /var/tmp/NVIDIA-Linux.run -aNqs --ui=none
  args:
    creates: /usr/lib64/xorg/modules/libnvidia-wfb.so.1
  ignore_errors: True

- name: Set DPI so fonts are sized properly
  template:
    dest: /etc/X11/xorg.conf.d/20-nvidia.conf
    src: 20-nvidia.conf.j2
