---
# docker.yml - configure Docker

- name: Directory for registry certs
  file:
    dest: "{{ docker.certs.path }}"
    state: directory
    mode: 0700

- name: Docker TLS CA cert
  copy:
    dest: "{{ docker.certs.path }}/{{ docker.certs.ca_root }}"
    src: certs/{{ docker.certs.ca_root }}
    mode: 0400

- name: Docker TLS cert
  copy:
    dest: "{{ docker.certs.path }}/docker-tls-cert.pem"
    src: certs/docker-tls-cert.pem
    mode: 0400

- name: Docker TLS key
  copy:
    dest: "{{ docker.certs.path }}/docker-tls-key.pem"
    content: "{{ vault_cert_keys.docker_tls }}"
    mode: 0400

- name: Registry SSL cert
  copy:
    dest: "{{ docker.certs.path }}/domain.crt"
    src: certs/registry-cert.pem
    mode: 0400

- name: Registry SSL key
  copy:
    dest: "{{ docker.certs.path }}/domain.key"
    content: "{{ vault_cert_keys.registry }}"
    mode: 0400

- name: Also add registry SSL cert to system's trusted CA root
  copy:
    dest: "{{ system_paths.ca_certs }}/docker-local.crt"
    src: certs/registry-cert.pem
    mode: 0400
  notify: Update CA certificates

- name: Thin pool create
  lvol:
    lv: thinpool
    vg: data01
    size: "{{ docker.thinpool.size }}"

- name: Thin pool meta
  lvol:
    lv: thinpoolmeta
    vg: data01
    size: "{{ docker.thinpool.meta_size }}"

- name: Convert thinpool
  command: >
    lvconvert -y --zero n -c 512K --thinpool data01/thinpool
      --poolmetadata data01/thinpoolmeta
  args:
    creates: /dev/mapper/data01-thinpool_tdata

- name: LVM profile path
  file:
    dest: /etc/lvm/profile
    state: directory

- name: Define thinpool autoextend
  template:
    dest: /etc/lvm/profile/data01-thinpool.profile
    src: thinpool.profile.j2
  notify: Activate thinpool autoextend

- name: Docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial edge
    filename: docker

- name: Temporarily disable systemctl start
  copy:
    content: "#/bin/sh\necho Disabled by ansible: systemctl start\nexit 101\n"
    dest: /usr/sbin/policy-rc.d
  changed_when: false

- name: Docker engine package
  apt:
    name: docker-ce
    update_cache: yes

- name: Docker options
  copy:
    content: "{{ docker.options|to_nice_json }}"
    dest: /etc/docker/daemon.json
  notify: Restart docker

- name: Deal with conflicting systemd-unit option if present
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: "ExecStart=.*"
    line: ExecStart=/usr/bin/dockerd
  ignore_errors: true
  notify: Reload systemd

- name: Systemd unit file for enabling /var/lib/docker/volumes monitoring
  copy:
    dest: /etc/systemd/system/docker-permissions.service
    src: docker-permissions.service

- name: Systemd unit file for post-startup docker commands
  copy:
    dest: /etc/systemd/system/docker-local@.service
    src: docker-local@.service

- name: Reenable systemctl start
  file:
    dest: /usr/sbin/policy-rc.d
    state: absent
  changed_when: false

- name: docker-nonat script for MythTV
  copy:
    dest: /usr/local/bin/docker-nonat.sh
    src: docker-nonat.sh
    mode: 0755
  
- name: Enable docker-permissions.service
  systemd:
    name: docker-permissions
    enabled: yes

- name: Docker service
  service:
    name: docker
    state: started
