---
# main.yml

# Set up all packages, volumes, security definitions and services
#  for a docker swarm node

- include: security.yml
- include: repos.yml
- include: kernel.yml
- include: packages.yml
- include: docker.yml
