---
# package.yml

- name: Install system packages
  apt:
    name: "{{ ubuntu_packages }}"

- name: Install local additions
  apt:
    name: "{{ ubuntu_package_additions }}"

- name: Python pip package
  apt:
    name: python3-pip
  when: ansible_distribution_version >= '20.04'

- name: Python pip package
  apt:
    name: python-pip
  when: ansible_distribution_release < '20.04'
