---
# package.yml

- name: Install system packages
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_packages }}"

- name: Install local additions
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_package_additions }}"
