---
- name: Disable local sources
  replace:
    dest: /etc/apt/sources.list
    replace: "# deb ftp://ovulator.ci.net removed"
    regexp: "^deb ftp://ovulator.ci.net/.*(updates|backports|iverse).*"

- name: Ensure repos available
  apt_repository:
    repo: "{{ item }}"
    filename: ubuntu
  with_items: "{{ ubuntu_repos }}"
