---
# security.yml

# This is customized: replace with your own security policies

- name: Adjust TCP keepalive to preserve management sessions
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: '86400'
    sysctl_set: yes

- name: Install rrsync for rsnapshot backups
  copy:
    dest: /usr/local/bin/rrsync
    src: rrsync
    force: no
    mode: 0755
