---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  clusterIP: $WXCAM_UPLOAD_IP
  ports:
  - { port: 21, targetPort: 21, name: ftp }
  - { port: 30091, targetPort: 30091, name: pasv1 }
  - { port: 30092, targetPort: 30092, name: pasv2 }
  - { port: 30093, targetPort: 30093, name: pasv3 }
  - { port: 30094, targetPort: 30094, name: pasv4 }
  - { port: 30095, targetPort: 30095, name: pasv5 }
  - { port: 30096, targetPort: 30096, name: pasv6 }
  - { port: 30097, targetPort: 30097, name: pasv7 }
  - { port: 30098, targetPort: 30098, name: pasv8 }
  - { port: 30099, targetPort: 30099, name: pasv9 }
  - { port: 30100, targetPort: 30100, name: pasv10 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: CAMS, value: $WXCAM_CAMS }
        - { name: PASV_ADDRESS, value: $WXCAM_UPLOAD_IP }
        - { name: UPLOAD_USERNAME, value: $WXCAM_UPLOAD_USERNAME }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        ports:
        - containerPort: 21
        - containerPort: 30090
        - containerPort: 30091
        - containerPort: 30092
        - containerPort: 30093
        - containerPort: 30094
        - containerPort: 30095
        - containerPort: 30096
        - containerPort: 30097
        - containerPort: 30098
        - containerPort: 30099
        - containerPort: 30100
        volumeMounts:
        - mountPath: /home/wx/upload
          name: share
          subPath: wx
        - name: wunderground-user-password
          mountPath: /run/secrets/wunderground-user-password
          readOnly: true
          subPath: wunderground-user-password
        - name: wxcam-password-hashed
          mountPath: /run/secrets/wxcam-password-hashed
          readOnly: true
          subPath: wxcam-password-hashed
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: wunderground-user-password
        secret:
          secretName: wunderground-user-password
      - name: wxcam-password-hashed
        secret:
          secretName: wxcam-password-hashed
