version: "3"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/samba:latest
    network_mode: host
    restart: always
    environment:
      NETBIOS_NAME: ${SAMBA_NETBIOS_NAME:-samba}
      SERVER_STRING: ${SAMBA_SERVER_STRING:-Samba Server}
      TZ: US/Pacific
      WORKGROUP: ${SAMBA_WORKGROUP:-WORKGROUP}
    volumes:
    - ${ADMIN_PATH}/samba/etc:/etc/samba/conf.d:ro
    - ${SHARE_PATH}/samba/var/lib:/var/lib/samba
    - log:/var/log/samba
    - ${SHARE_PATH}/user:/home
    - ${SHARE_PATH}/dos:/pc/dos
    - ${SHARE_PATH}/household:/pc/Household
    - /pc/MP3:/pc/MP3
    - /pc/Pictures:/pc/Pictures
    - /var/ftp:/var/ftp:ro
    ports:
    - 137-138:137-138/udp
    - 139:139
    - 445:445
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}

volumes:
  log:
  dos:
  household:
