---

- name: Restart journald
  service:
    name: systemd-journald
    state: restarted

- name: Restart NRPE
  service:
    name: "{{ nagios.nrpe_service }}"
    state: restarted

- name: Restart rsyslogd
  service:
    name: rsyslog
    state: restarted

- name: Restart snmpd
  service:
    name: snmpd
    state: restarted
