---
# main.yml

# Handlers for services and management actions

- name: Restart docker
  service:
    name: docker
    state: restarted

- name: Restart rsyslogd
  service:
    name: rsyslog
    state: restarted

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Reload systemd
  systemd:
    name: docker.service
    daemon_reload: yes

- name: Activate thinpool autoextend
  shell: >
    lvchange --metadataprofile {{ vg }}-thinpool {{ vg }}/thinpool &&
    lvs -o+seg_monitor

- name: Update CA certificates
  command: update-ca-certificates
