---
# main.yml

# Handlers for services and management actions

- name: Restart docker
  service:
    name: docker
    state: restarted

- name: Restart ntpd
  service:
    name: ntp
    state: restarted

- name: Restart rsyslogd
  service:
    name: rsyslog
    state: restarted

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Reload systemd
  systemd:
    name: docker.service
    daemon_reload: yes

- name: Activate thinpool autoextend
  shell: >
    lvchange --metadataprofile data01-thinpool data01/thinpool &&
    lvs -o+seg_monitor

# This (slow) installation is defined here as a handler because the 
#  apt module lacks an idempotency check to prevent re-downloading

- name: Updated kernel image (amd64)
  apt:
    deb: "{{ kernel.origin }}/v{{ kernel.version }}/linux-image-{{
      kernel.version }}-{{ kernel.short_ver }}-generic_{{
      kernel.long_ver }}_amd64.deb"
