version: "3"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/spamassassin:${VERSION_SPAMASSASSIN:-latest}
    environment:
      EXTRA_OPTIONS: --nouser-config --sql-config
    ports:
    - ${PORT_SPAMASSASSIN:-783}:783
    volumes:
    - ${ADMIN_PATH:-/opt}/spamassassin/etc/local.cf:/etc/mail/spamassassin/local.cf:ro
    - home:/var/lib/spamassassin
    - logs:/var/log
    deploy:
      mode: global
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 10

networks:
  default:
    external:
      name: app_net
volumes:
  home:
  logs:
