---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  clusterIP: $SPAMASSASSIN_IP
  ports:
  - name: $SERVICE_NAME
    port: 783
    targetPort: 783
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
    release: "0.1"
  name: $SERVICE_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
      release: "0.1"
  serviceName: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
        release: "0.1"
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: EXTRA_OPTIONS, value: --nouser-config --sql-config }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        ports:
        - containerPort: 783
        volumeMounts:
        - mountPath: /etc/mail/spamassassin/local.cf
          name: admin
          readOnly: true
          subPath: $SERVICE_NAME/etc/local.cf
        - mountPath: /var/lib/spamassassin
          name: home
        - mountPath: /var/log
          name: logs
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: home
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 50Mi
