version: "3"

services:
  app:
    image: dockerhub.instantlinux.net:5000/spamassassin:latest
    environment:
      EXTRA_OPTIONS: --nouser-config --sql-config
    ports:
    - 783:783
    volumes:
    - /var/lib/docker/share/spamd/etc/local.cf:/etc/mail/spamassassin/local.cf:ro
    - home:/var/lib/spamassassin
    - logs:/var/log
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync-member == true
      replicas: 2
    networks:
      app_net:

networks:
  app_net:
    external: true
volumes:
  home:
  logs:
