---
# set up a MythTV frontend

# Usage:
#
#  ansible-playbook frontend-setup.yml

- hosts: mythfrontends
  become: True
  force_handlers: True
  roles:
  - users
  - network
  - monitoring_agent
  - mythfrontend
  - ntp
  - volumes
