---
# set up a Docker node

# Usage:
#
#  ansible-playbook node-setup.yml

- hosts: swarm_nodes
  become: True
  force_handlers: True
  roles:
  - docker_node
  - { role: docker_network, tags: network }
  - { role: monitoring_agent, tags: nagios }
  - { role: ntp, tags: ntp }
