---
- name: Define enable dhcp-enable status for netplan
  set_fact:
    netplan_netcfg: "{{ netplan_netcfg|combine(
        {'network': {'ethernets': {network.interface: {
         'dhcp4': network.mode != 'static'}}}},
        recursive=True) }}"

- name: Define netplan configuration
  template:
    dest: /etc/netplan/01-netcfg.yaml
    src: netplan.j2
  notify: Netplan apply
