---

network_defaults:
  address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  bridge: null
  device_name: enp1s0
  gateway: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['gateway'] }}"
  interface: enp1s0
  mode: dhcp
  nameservers: "{{ hostvars[inventory_hostname]['ansible_dns']['nameservers'] }}"
  netmask: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['netmask'] }}"
  search: "{{ hostvars[inventory_hostname]['ansible_dns']['search'] }}"
  swarm_ip: null

network_override: {}
network: "{{ network_defaults | combine(network_override) }}"

ubuntu_packages:
  - bridge-utils
  - dnsutils
  - keepalived
  - psmisc

vrrp:
  VI_1:
    id: 50
    ip: "{{ network.swarm_ip }}"
    interface: "{{ network.device_name }}"
    priority: "{{ network.address.split('.')[3] }}"
    unicast_peers: "{{ groups['swarm_nodes'] | map('extract', hostvars,
                       ['ansible_default_ipv4', 'address']) | list |
                       difference([network.address]) }}"
