---
- name: Restart keepalived
  service:
    enabled: yes
    name: keepalived
    state: restarted

- name: Netplan apply
  command: netplan apply

- name: Restart sshd
  service:
    name: sshd
    state: restarted
