version: "3.1"
# Synchronize two swarm nodes
#  Note that the stack has to be redeployed any time a new volume
#  mount is added underneath the top-level share

services:

  primary:
    image: dockerhub.instantlinux.net:5000/swarm-sync:latest
    environment:
      SYNC_INTERVAL: "2"
      TZ: US/Pacific
    volumes:
    - logs:/var/log/unison
    - syncarchive:/root/.unison
    - /var/lib/docker/share:/var/swarm-sync
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary
    networks:
    - sync
    secrets:
    - swarm-sync_sshkey

  peer:
    image: dockerhub.instantlinux.net:5000/swarm-sync:latest
    environment:
      SYNC_ROLE: peer
    env_file:
    - ../../.docker/swarm-sync.pub.env
    volumes:
    - /var/lib/docker/share:/var/swarm-sync
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == peer
    networks:
    - sync

networks:
  sync:
volumes:
  logs:
  syncarchive:
secrets:
  swarm-sync_sshkey:
    external: true
