---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
spec:
  ports:
  - { port: 3306, targetPort: 3306 }
  clusterIP: None
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
    release: "0.1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
    release: "0.1"
  name: $SERVICE_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
      release: "0.1"
  serviceName: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
        release: "0.1"
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: CLUSTER_NAME, value: $SERVICE_NAME }
        - { name: DISCOVERY_SERVICE, value: "etcd-etcd:2379" }
        - { name: CLUSTER_SIZE, value: "3" }
        image: $REGISTRY_URI/mariadb-galera:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /etc/mysql/my.cnf.d
          name: config
          readOnly: true
          subPath: mariadb/etc
        - mountPath: /var/log/mysql
          name: logs
        - mountPath: /var/lib/mysql
          name: data
        - name: mysql-root-password
          mountPath: /run/secrets/mysql-root-password
          readOnly: true
          subPath: mysql-root-password
        - name: sst-auth-password
          mountPath: /run/secrets/sst-auth-password
          readOnly: true
          subPath: sst-auth-password
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: config
        hostPath: { path: $PATH_ADM }
      - name: mysql-root-password
        secret:
          secretName: mysql-root-password
      - name: sst-auth-password
        secret:
          secretName: sst-auth-password
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 8Gi
  - metadata:
      name: logs
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 500Mi
