---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  ports:
  - { port: $PORT_HAPROXY_STATS, targetPort: 8080 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: KEEPALIVED_CONFIG_ID, value: $KEEPALIVED_CONFIG_ID }
        image: $REGISTRY_URI/$SERVICE_NAME:latest
        securityContext:
          capabilities:
            add: [ NET_ADMIN ]
        volumeMounts:
        - name: admin
          mountPath: /etc/haproxy.d
          readOnly: true
          subPath: services/haproxy/etc-k8s
        - name: admin
          mountPath: /etc/keepalived/keepalived.conf
          readOnly: true
          subPath: services/keepalived/etc-k8s/keepalived.conf
        - name: secret
          mountPath: /run/secrets/haproxy-stats-password
          readOnly: true
          subPath: haproxy-stats-password
      hostNetwork: true
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      nodeSelector:
        service.$SERVICE_NAME: allow
      serviceAccountName: $K8S_NAMESPACE-privileged
      volumes:
      - name: admin
        hostPath: { path: $PATH_ADM }
      - name: secret
        secret:
          secretName: haproxy-stats-password
