version: "3.1"

services:

  app:
    image: ${REGISTRY_URI:-instantlinux}/postfix-python:latest
    environment:
      DB_HOST: xdb00
      CIDR_MIN_SIZE: 27
      INBOUND_RELAY: by mx-caprica.?\.easydns\.com
      SPAMC_HOST: spamd00.ci.net
    volumes:
    - /var/lib/docker/volumes/admin/_data/services/postfix/etc/:/etc/postfix/postfix.d:ro
    - /var/lib/docker/share/common/pki/certs:/etc/ssl/certs:ro
    - spool:/var/spool/postfix
    ports:
    - 3525:25
    secrets:
    - mysql-blacklist-user
    - postfix-sasl-passwd
    - webmail.ci.net-server-key.pem 

volumes:
  spool:
networks:
  default:
    external:
      name: app_net
secrets:
  mysql-blacklist-user:
    external: true
  postfix-sasl-passwd:
    external: true
  webmail.ci.net-server-key.pem:
    external: true
