version: "3.1"

services:

  app:
    image: ${REGISTRY_URI:-instantlinux}/postfix-python:${VERSION_POSTFIX:-latest}
    environment:
      DB_HOST: ${DB_HOST:-db}
      CIDR_MIN_SIZE: ${CIDR_MIN_SIZE:-32}
      HONEYPOT_ADDRS: ${HONEYPOT_ADDRS:-none}
      INBOUND_RELAY: by mx-caprica.?\.easydns\.com
      SPAMC_HOST: ${SPAMC_HOST:-spamd}
      TZ: ${TZ:-UTC}
    volumes:
    - ${ADMIN_PATH:-/opt}/postfix/etc/:/etc/postfix/postfix.d:ro
    - ${SHARE_PATH}/common/pki/certs:/etc/ssl/certs:ro
    - spool:/var/spool/postfix
    ports:
    - ${PORT_POSTFIX_INTERNAL:-25}:25
    - ${PORT_POSTFIX_EXTERNAL:-3525}:3525
    secrets:
    - mysql-blacklist-user
    - postfix-sasl-passwd
    - webmail.ci.net-server-key.pem 
    deploy:
      mode: global
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 10

volumes:
  spool:
secrets:
  mysql-blacklist-user:
    external: true
  postfix-sasl-passwd:
    external: true
  webmail.ci.net-server-key.pem:
    external: true
