---

db_defaults:
  host: db00
  user: mythtv
  name: mythtv
  context: local

display_driver_defaults:
  type: nvidia
  download: False
  nvidia:
    checksum: d2cf81b5994a1728dc4851cdf0480cde0a34b040c94de0d5265edcfe3b90680a
    creates: /usr/lib64/xorg/modules/libnvidia-wfb.so.1
    download_uri: http://us.download.nvidia.com/XFree86/Linux-x86_64
    version: 340.101
  packages:
  - nvidia-304
  screen:
    modes:
    - 1280x720
    - 1920x1080
    - 1980x1080i
display_driver: "{{ display_driver_defaults | combine(display_driver_overrides) }}"

ir_device:
  device: /dev/lirc0
  module: lirc_mceusb2
  product_name: Media Center Ed. eHome Infrared Remote Transceiver (1784:0008)
  service_name: lirc

mythdb_overrides: {}
db: "{{ db_defaults | combine(mythdb_overrides) }}"

mythtv_version: 0.29

opensuse_packages:
  - ImageMagick-devel
  - kdm
  - libdvdcss
  - liblirc_client0=0.9.0
  - lirc=0.9.0
  - lirc-remotes=0.9.0
  - kernel-default
  - kernel-devel
  - kernel-headers
  - kernel-source
  - mythtv-frontend
  - MozillaFirefox
  - mariadb-client
  - mythtv-base-themes
  - mythtv-common
  - nrpe
  - nagios-plugins
  - net-snmp
  - ntp
  - patterns-openSUSE-kde4
  - perl-Crypt-DES
  - perl-mythtv
  - perl-Net-CIDR
  - perl-Net-Server
  - perl-Net-SNMP
  - perl-TimeDate
  - python-mysql
  - python-mythtv
  - rsyslog
  - v4l-utils
  - xdm
  - xkeyboard-config
  - xorg-x11-driver-input
  - xorg-x11-driver-video
  - xorg-x11-fonts

opensuse_repo_defaults:
  - name: oss
    repo: http://download.opensuse.org/distribution/leap/42.2/repo/oss/suse
  - name: ossupd
    repo: http://download.opensuse.org/update/leap/42.2/oss/
  - name: packman
    repo: http://packman.inode.at/suse/openSUSE_Leap_42.2/
    flags: -f --keep-packages

opensuse_repo_additions: []
opensuse_repos: "{{ opensuse_repo_defaults + opensuse_repo_additions }}"

network_defaults:
  address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  gateway: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['gateway'] }}"
  interface: enp0s10
  mode: dhcp
  module: False
  nameservers: "{{ hostvars[inventory_hostname]['ansible_dns']['nameservers'] }}"
  netmask: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['netmask'] }}"
  search: "{{ hostvars[inventory_hostname]['ansible_dns']['search'] }}"
  vrrp_interface: null

network_override: {}
network: "{{ network_defaults | combine(network_override) }}"

# To disable this feature, override suspend to False
suspend:
  hour: 0
  minute: 30
  wake_hour: 17
  wake_minute: 30
  weekday: 1-5

ubuntu_apt_keys:
  # google: 1397BC53640DB551
  graphics: FCAE110B1118213C
  mythbuntu: 13551B881504888C

ubuntu_packages:
  - evtest
  - google-chrome-stable
  - ir-keytable
  - libdvd-pkg
  - mariadb-client
  - mythtv-common
  - mythtv-frontend
  - kde-plasma-desktop
  - xserver-xorg-core
  - xserver-xorg-input-all
  - xterm

ubuntu_repo_uri: http://archive.ubuntu.com/ubuntu/

ubuntu_repo_defaults:
  - deb {{ ubuntu_repo_uri }} {{ ansible_distribution_release
        }} main restricted universe multiverse
  - deb {{ ubuntu_repo_uri }} {{ ansible_distribution_release
        }}-updates main restricted universe multiverse
  - deb {{ ubuntu_repo_uri }} {{ ansible_distribution_release
        }}-backports main restricted universe multiverse
  - deb {{ ubuntu_repo_uri }} {{ ansible_distribution_release
        }}-security main restricted universe multiverse

ubuntu_repo_additions:
  - deb http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu {{
    ansible_distribution_release }} main
  - deb http://ppa.launchpad.net/mythbuntu/{{ mythtv_version }}/ubuntu {{
    ansible_distribution_release }} main
  - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

ubuntu_repos: "{{ ubuntu_repo_defaults + ubuntu_repo_additions }}"
