---
# cifs.yml

- name: Credentials for CIFS mounts
  copy:
    dest: "{{ cifs_credentials.file }}"
    content: "username={{ cifs_credentials.remote_user
      }}\npassword={{ vault_cifs_credentials.remote_password }}\n"
    mode: 0400

