---
# main.yml

- name: Install system packages
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_packages }}"
  when: ansible_os_family == 'Debian'

- name: Create mount points
  command: mkdir -p {{ item.value.path }}
  args:
    creates: "{{ item.value.path }}"
  with_dict: "{{ volumes[vg] | combine(network_mounts) |
                 combine(local_volumes) }}"

- name: Create volumes
  lvol:
    lv: "{{ item.key }}"
    vg: "{{ vg }}"
    shrink: no
    size: "{{ item.value.size }}"
  with_dict: "{{ volumes[vg] }}"
  notify:
  - Cryptsetup resize
  - Filesystem resize

- include: encrypted.yml
  when: volumes[vg]

- include: cifs.yml

- name: Network and local fstab entries
  mount:
    fstype: "{{ item.value.type if 'type' in item.value else fs_type }}"
    path: "{{ item.value.path }}"
    src: "{{ item.key }}"
    opts: "{{ item.value.options if 'options' in item.value else 'default' }}"
    state: mounted
  with_dict: "{{ network_mounts | combine(local_volumes) }}"
